"""add audit closure fields to audits table

Revision ID: 2d24c946bcb1
Revises: 320043160088
Create Date: 2026-09-12 22:47:09.695404
"""
from alembic import op
import sqlalchemy as sa


revision = '2d24c946bcb1'
down_revision = '320043160088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('findings_checklist_item_id_fkey'), 'findings', type_='foreignkey')
    # Error en: db/migrations/versions/2d24c946bcb1_add_audit_closure_fields_to_audits_table.py
    op.create_foreign_key(None, 'findings', 'checklist_items', ['checklist_item_id'], ['id'])
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_tenant_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'tenants', ['tenant_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'clients', ['client_id'], ['id'], source_schema='public', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_client_id_fkey1'), 'memberships', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('memberships_tenant_id_fkey'), 'memberships', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(op.f('findings_checklist_item_id_fkey'), 'findings', 'audit_checklist_items', ['checklist_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
