"""add_audit_closure_columns_to_audits

Revision ID: 3d8d0611fa34
Revises: 9f0cb9027dda
Create Date: 2026-09-14 15:46:05.617065
"""
from alembic import op
import sqlalchemy as sa


revision = '3d8d0611fa34'
down_revision = '9f0cb9027dda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audits', sa.Column('closed_by_id', sa.Uuid(), nullable=True))
    op.add_column('audits', sa.Column('closing_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'audits', 'users', ['closed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.drop_column('audits', 'closing_summary')
    op.drop_column('audits', 'closed_by_id')
    op.drop_column('audits', 'closed_at')
    # ### end Alembic commands ###
