"""add_findings_timestamps_and_checklist_summary

Revision ID: 4d017e6497c3
Revises: 0002
Create Date: 2026-09-12 15:20:02.697997
"""
from alembic import op
import sqlalchemy as sa


revision = '4d017e6497c3'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memberships_tenant_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'tenants', ['tenant_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'clients', ['client_id'], ['id'], source_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('memberships_client_id_fkey'), 'memberships', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('memberships_tenant_id_fkey'), 'memberships', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
