"""add_missing_findings_and_checklist_columns

Revision ID: 7deb13f74599
Revises: 3d8d0611fa34
Create Date: 2026-09-14 16:05:38.684303
"""
from alembic import op
import sqlalchemy as sa


revision = '7deb13f74599'
down_revision = '3d8d0611fa34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('findings_summary', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('findings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('findings', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'closed_at')
    op.drop_column('findings', 'updated_at')
    op.drop_column('findings', 'created_at')
    op.drop_column('checklist_items', 'findings_summary')
    # ### end Alembic commands ###
